<?php
require('config.php');
switch($LANGUAGE){
case 'fr':
define('sortby','Trier par…');
define('name','Titre');
define('original_name', 'Titre original');
define('year','Ann&eacute;e');
define('note','Note');
define('display','Affichage par genre');
define('genre','Genre');
define('home','Accueil');
define('research','Recherche');
define('files','fichier(s)');
define('folders','dossier(s)');
define('pagegeneration','Page g&eacute;n&eacute;r&eacute;e en');
define('loading','Chargement');
define('details','Fiche détaillée');
define('update','Modifier');
define('link', 'Lien');
define('infos', 'Infos');
define('delinfos', 'Supprime infos');
define('length','Longueur');
define('votes','Votes');
define('country','Pays');
define('genres','Genres');
define('director','R&eacute;alisateur');
define('actors','Acteurs');
define('synopsis','Synopsis');
define('trailer','Trailer');
define('season','Saison');
define('episode','Episode');
define('nbepisode','Nombre d\'&eacute;pisodes');			
define('administration','Administration');
define('basicparameters','Param&egrave;tres de base');
define('nonindexedvideos','Vid&eacute;os non index&eacute;es');
define('wrongindexedvideos','Vid&eacute;os mal index&eacute;es');
define('donate','Faire un don');
define('donatetext','Cette application vous pla&icirc;t? N\'h&eacute;sitez pas &agrave; faire un petit geste &agrave; son cr&eacute;ateur :)<br>Merci!');
define('appname','Nom de l\'application');
define('version', 'Version');
define('login','Login');
define('secureconnexion', 'Connexion https');
define('modal','Fen&ecirc;tre modal');
define('ftp','FTP');
define('autoindexing','Indexation automatique');
define('dbmovies','Base de donn&eacute;es vid&eacute;os');
define('dbseries','Base de donn&eacute;es s&eacute;ries');
define('lang','Langue');
define('sqluser','Utilisateur MySQL');
define('sqlpass','Mot de passe MySQL');
define('dbsql','Base de donn&eacute;es MySQL');
define('videodir','R&eacute;pertoire des vid&eacute;os');
define('seriesdir','R&eacute;pertoire des s&eacute;ries');
define('videoext','Extensions des vid&eacute;os');
define('hidden_files','Fichiers/Dossiers cach&eacute;s');
define('deleted_words','Mots &agrave; effacer');
define('username','Nom d\'utilisateur');
define('password','Mot de passe');
define('rememberme','Se souvenir de moi');
define('indexing','Indexation en cours…');
define('warning1','Ce changement va effacer votre base');
define('warning2','Veuillez vous loguer en tant qu\'administrateur');
break;

case 'en':
define('sortby','Sort by...');
define('name','Title');
define('original_name', 'Original title');
define('year','Year');
define('note','Score');
define('display','Display by genre');
define('genre','Genre');
define('home','Home');
define('research','Research');
define('files','file(s)');
define('folders','folder(s)');
define('pagegeneration','Page generation :');
define('loading','Loading');
define('details','Detailed sheet');
define('update','Update');
define('link', 'Link');
define('infos', 'Infos');
define('delinfos', 'Delete infos');
define('length','Length');
define('votes','Votes');
define('country','Countries');
define('genres','Genres');
define('director','Directors');
define('actors','Actors');
define('synopsis','Synopsis');
define('trailer','Trailer');
define('season','Season');
define('episode','Episode');
define('nbepisode','Number of episodes');			
define('administration','Administration');
define('basicparameters','Basics parameters');
define('nonindexedvideos','Non indexed videos');
define('wrongindexedvideos','Wrong indexed videos');
define('donate','Donate');
define('donatetext','Like this app? Feel free to pay a beer to its creator :)<br>Thanks!');
define('appname','Application name');
define('version', 'Version');
define('login','Login');
define('secureconnexion', 'https connexion');
define('modal','Modal windows');
define('ftp','FTP');
define('autoindexing','Auto-indexing');
define('dbmovies','Movies Database');
define('dbseries','Series Database');
define('lang','Language');
define('sqluser','MySQL user');
define('sqlpass','MySQL paswword');
define('dbsql','MySQL database');
define('confport','Admin port');
define('videodir','Video dir');
define('seriesdir','Series dir');
define('videoext','Videos extensions');
define('hidden_files','Files/Folders hidden');
define('deleted_words','Words to delete');
define('username','Username');
define('password','Password');
define('rememberme','Remember me');
define('indexing','Indexing...');
define('warning1','This change will delete your database');
define('warning2','Please login as administrator');
break;
}

?>